printWidth: 120
tabWidth: 4
useTabs: false
semi: true
singleQuote: true
quoteProps: preserve
jsxSingleQuote: true
trailingComma: all
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: avoid
htmlWhitespaceSensitivity: strict
endOfLine: lf
